### ISSUE TITLE
Hello, i'm a student, and interested in your project, can u provide your pre-trained model?

### ISSUE THREAD

**Issue by simay233** [joffery/GC-GAN#4]
Excuse me for interrupting，i want to use GANs generate a neutral expression, but it seems diffuclt to train a well GANs model, i'm very helpless about this。

**Comment by joffery** [comment]
Hi @simay233 ,

Thanks for your interest in our work! I have left my previous institute for a long time and I do not have access to the datasets. I will upload a pretrained model once I get the datasets.

There are several excellent projects using GANs to generate facial expressions:
https://github.com/yunjey/StarGAN
https://github.com/donydchen/ganimation_replicate
Hope these projects can help you.

Best,
Fengchun
